### PR TITLE
Support angular 18

### PR DESCRIPTION
**Pull request by MaximBelov**

### CODE REVIEW

**Comment by gund** [comment]
Can you please explain why are you trying to update this library to angular v18?
I'm not doing any updates to it by design, to maintain backwards compatibility with previous angular versions for as long as possible, pretty much until angular itself will break support in some future version with libraries built with older compilers.
This has been pointed our multiple times in #513, #516, #512.
Are you having some issues with this library specifically in angular v18 and if so which ones?

**Comment by MaximBelov** [comment]
Hi 
Sorry, I thought there was no activity and decided to check for possible updates. 

In any case, I will continue to use my updated version and let you know if I have any problems.

For now, I'm marking this PR as a draft or we can make a version  11.0.0-alpha(next)

**Comment by gund** [comment]
> we can make a version 11.0.0-alpha(next)

I still did not get why do you want to update this library?

**Comment by gund** [comment]
Closing to keep repo clean.
If you want to contribute you are welcome, but first please discuss if we are actually interested in something like an upgrade, as for now we will not update the lib to latest version to prolong backwards compatibility for as long as possible.

**Pull request closed without merging**
