### PR TITLE
Fix issues with barrel files and ng-packagr

### PR DESCRIPTION
**Pull request by berrygoudswaard**
I was trying to use your fantastic library in my own library but wasn't able to build. 

After some investigation it turns out that ng-packagr isn't playing nice with barrel files (the index.ts files in your project). See also https://github.com/ng-packagr/ng-packagr/issues/1173

The error is got during compilation was: 
```bash
ERROR: Unexpected value 'undefined' imported by the module 'DynamicComponentModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'
Unexpected value 'undefined' exported by the module 'DynamicComponentModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'
Unexpected value 'undefined' exported by the module 'DynamicModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'

An unhandled exception occurred: Unexpected value 'undefined' imported by the module 'DynamicComponentModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'
Unexpected value 'undefined' exported by the module 'DynamicComponentModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'
Unexpected value 'undefined' exported by the module 'DynamicModule in ./node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'
```

# Reproduction
With Angular CLI: 9.1.0

```bash
ng new test-project --create-application=false
cd test-project
npm install ng-dynamic-component@6.1.0
ng g library testlib
```

now edit `projects/testlib/src/lib/testlib.module.ts` so that it looks like:
```typescript
import { NgModule } from '@angular/core';
import { TestlibComponent } from './testlib.component';

import { DynamicComponentModule } from 'ng-dynamic-component';


@NgModule({
  declarations: [TestlibComponent],
  imports: [
    DynamicComponentModule
  ],
  exports: [TestlibComponent]
})
export class TestlibModule { }
```

Finally run `ng build --prod`

### CODE REVIEW

**Comment by gund** [comment]
Hi @berrygoudswaard and thank you for taking time and submitting this PR!

I was able to reproduce this error following your steps. However I'm using this library also in another project (inside NX workspace) in another library just like in your use-case and had no issues so far even though it's running latest angular packages like in the repro example.

Therefore I would like to postpone this fix and publish it temporarily under a separate tag (say `no-barrels`) until either it's fixed upstream or we figure out how is it not failing in current projects.

In the mean time, could you please run `npm run format` on this PR to fix CI?

**Comment by berrygoudswaard** [comment]
Hi Alex, 

I didn’t have this issue with version 6.0.0. The problem only occurs on version 6.1.0. Are using 6.1.0 in you NX workspace project?

I have done the formatting and just pushed the new version to Github

**Comment by gund** [comment]
Yes, I'm using latest `6.1.0` version and it compiles successfully with latest `ng-packagr` builder.

I will try to figure out why is it not breaking (or why is it breaking otherwise).

Also I can't see your commit for formatting fixes in this PR...

**Comment by gund** [comment]
I will merge this PR into `no-barrels` branch that will be released under `no-barrels` pre-relase tag in NPM.

**Pull request merged**
